services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - postgres
